fn:error() instance of xs:error
