try { fn:error() } catch * { $err:other }
