try {
  0
} catch err:* {
  "No error"
}
